
using System.Collections.Generic;
using TownOfHost.Roles.Core;

namespace TownOfHost;

class AddondataInfo
{
    public static string GetAddonMark(CustomRoles addon)
    {
        if (CustomRoles.NotAssigned < addon)
        {
            return addon switch
            {
                CustomRoles.Guesser => "∮",
                CustomRoles.Serial => "∂",
                CustomRoles.MagicHand => "ж",
                CustomRoles.Powerful => "∠",
                CustomRoles.Connecting => "Ψ",
                CustomRoles.Watching => "∑",
                CustomRoles.PlusVote => "р",
                CustomRoles.Tiebreaker => "т",
                CustomRoles.Autopsy => "Å",
                CustomRoles.Revenger => "Я",
                CustomRoles.Speeding => "∈",
                CustomRoles.Guarding => "ζ",
                CustomRoles.Management => "θ",
                CustomRoles.Opener => "п",
                CustomRoles.Seeing => "☯",
                CustomRoles.Lighting => "＊",
                CustomRoles.Moon => "э",
                //デバフ
                CustomRoles.SlowStarter => "Ｓs",
                CustomRoles.Notvoter => "Ｖ",
                CustomRoles.Elector => "Ｅ",
                CustomRoles.InfoPoor => "Ｉ",
                CustomRoles.NonReport => "Ｒ",
                CustomRoles.Transparent => "Ｔ",
                CustomRoles.Water => "Ｗ",
                CustomRoles.Clumsy => "Ｃ",
                CustomRoles.Slacker => "ＳＬ",
                CustomRoles.News => "Ｎ",
                CustomRoles.Crewmate => throw new System.NotImplementedException(),
                CustomRoles.Impostor => throw new System.NotImplementedException(),
                CustomRoles.Shapeshifter => throw new System.NotImplementedException(),
                CustomRoles.Phantom => throw new System.NotImplementedException(),
                CustomRoles.Viper => throw new System.NotImplementedException(),
                CustomRoles.BountyHunter => throw new System.NotImplementedException(),
                CustomRoles.FireWorks => throw new System.NotImplementedException(),
                CustomRoles.Mafia => throw new System.NotImplementedException(),
                CustomRoles.SerialKiller => throw new System.NotImplementedException(),
                CustomRoles.ShapeMaster => throw new System.NotImplementedException(),
                CustomRoles.Sniper => throw new System.NotImplementedException(),
                CustomRoles.Vampire => throw new System.NotImplementedException(),
                CustomRoles.Witch => throw new System.NotImplementedException(),
                CustomRoles.Warlock => throw new System.NotImplementedException(),
                CustomRoles.Mare => throw new System.NotImplementedException(),
                CustomRoles.Penguin => throw new System.NotImplementedException(),
                CustomRoles.Puppeteer => throw new System.NotImplementedException(),
                CustomRoles.TimeThief => throw new System.NotImplementedException(),
                CustomRoles.EvilTracker => throw new System.NotImplementedException(),
                CustomRoles.Stealth => throw new System.NotImplementedException(),
                CustomRoles.NekoKabocha => throw new System.NotImplementedException(),
                CustomRoles.EvilHacker => throw new System.NotImplementedException(),
                CustomRoles.Insider => throw new System.NotImplementedException(),
                CustomRoles.Bomber => throw new System.NotImplementedException(),
                CustomRoles.TeleportKiller => throw new System.NotImplementedException(),
                CustomRoles.AntiReporter => throw new System.NotImplementedException(),
                CustomRoles.Tairou => throw new System.NotImplementedException(),
                CustomRoles.Evilgambler => throw new System.NotImplementedException(),
                CustomRoles.Notifier => throw new System.NotImplementedException(),
                CustomRoles.Magician => throw new System.NotImplementedException(),
                CustomRoles.Decrescendo => throw new System.NotImplementedException(),
                CustomRoles.Curser => throw new System.NotImplementedException(),
                CustomRoles.Alien => throw new System.NotImplementedException(),
                CustomRoles.AlienHijack => throw new System.NotImplementedException(),
                CustomRoles.SpeedStar => throw new System.NotImplementedException(),
                CustomRoles.EvilTeller => throw new System.NotImplementedException(),
                CustomRoles.Limiter => throw new System.NotImplementedException(),
                CustomRoles.ProgressKiller => throw new System.NotImplementedException(),
                CustomRoles.Mole => throw new System.NotImplementedException(),
                CustomRoles.EvilAddoer => throw new System.NotImplementedException(),
                CustomRoles.Reloader => throw new System.NotImplementedException(),
                CustomRoles.Jumper => throw new System.NotImplementedException(),
                CustomRoles.EarnestWolf => throw new System.NotImplementedException(),
                CustomRoles.Amnesiac => throw new System.NotImplementedException(),
                CustomRoles.Camouflager => throw new System.NotImplementedException(),
                CustomRoles.ConnectSaver => throw new System.NotImplementedException(),
                CustomRoles.EvilSatellite => throw new System.NotImplementedException(),
                CustomRoles.ProBowler => throw new System.NotImplementedException(),
                CustomRoles.EvilMaker => throw new System.NotImplementedException(),
                CustomRoles.Eraser => throw new System.NotImplementedException(),
                CustomRoles.QuickKiller => throw new System.NotImplementedException(),
                CustomRoles.CharismaStar => throw new System.NotImplementedException(),
                CustomRoles.Ballooner => throw new System.NotImplementedException(),
                CustomRoles.BorderKiller => throw new System.NotImplementedException(),
                CustomRoles.ShapeKiller => throw new System.NotImplementedException(),
                CustomRoles.Archer => throw new System.NotImplementedException(),
                CustomRoles.Assassin => throw new System.NotImplementedException(),
                CustomRoles.EvilBlender => throw new System.NotImplementedException(),
                CustomRoles.UnFortuner => throw new System.NotImplementedException(),
                CustomRoles.Bloodlust => throw new System.NotImplementedException(),
                CustomRoles.MadGuardian => throw new System.NotImplementedException(),
                CustomRoles.Madmate => throw new System.NotImplementedException(),
                CustomRoles.MadSnitch => throw new System.NotImplementedException(),
                CustomRoles.MadAvenger => throw new System.NotImplementedException(),
                CustomRoles.SKMadmate => throw new System.NotImplementedException(),
                CustomRoles.MadJester => throw new System.NotImplementedException(),
                CustomRoles.MadTeller => throw new System.NotImplementedException(),
                CustomRoles.MadBait => throw new System.NotImplementedException(),
                CustomRoles.MadReduced => throw new System.NotImplementedException(),
                CustomRoles.MadWorker => throw new System.NotImplementedException(),
                CustomRoles.MadTracker => throw new System.NotImplementedException(),
                CustomRoles.MadChanger => throw new System.NotImplementedException(),
                CustomRoles.MadSuicide => throw new System.NotImplementedException(),
                CustomRoles.MadBetrayer => throw new System.NotImplementedException(),
                CustomRoles.Nue => throw new System.NotImplementedException(),
                CustomRoles.Engineer => throw new System.NotImplementedException(),
                CustomRoles.Scientist => throw new System.NotImplementedException(),
                CustomRoles.Tracker => throw new System.NotImplementedException(),
                CustomRoles.Noisemaker => throw new System.NotImplementedException(),
                CustomRoles.Detective => throw new System.NotImplementedException(),
                CustomRoles.Bait => throw new System.NotImplementedException(),
                CustomRoles.Lighter => throw new System.NotImplementedException(),
                CustomRoles.Mayor => throw new System.NotImplementedException(),
                CustomRoles.SabotageMaster => throw new System.NotImplementedException(),
                CustomRoles.Sheriff => throw new System.NotImplementedException(),
                CustomRoles.Snitch => throw new System.NotImplementedException(),
                CustomRoles.SpeedBooster => throw new System.NotImplementedException(),
                CustomRoles.Trapper => throw new System.NotImplementedException(),
                CustomRoles.Dictator => throw new System.NotImplementedException(),
                CustomRoles.Doctor => throw new System.NotImplementedException(),
                CustomRoles.Seer => throw new System.NotImplementedException(),
                CustomRoles.TimeManager => throw new System.NotImplementedException(),
                CustomRoles.Gasp => throw new System.NotImplementedException(),
                CustomRoles.VentMaster => throw new System.NotImplementedException(),
                CustomRoles.ToiletFan => throw new System.NotImplementedException(),
                CustomRoles.Bakery => throw new System.NotImplementedException(),
                CustomRoles.FortuneTeller => throw new System.NotImplementedException(),
                CustomRoles.TaskStar => throw new System.NotImplementedException(),
                CustomRoles.PonkotuTeller => throw new System.NotImplementedException(),
                CustomRoles.UltraStar => throw new System.NotImplementedException(),
                CustomRoles.MeetingSheriff => throw new System.NotImplementedException(),
                CustomRoles.GuardMaster => throw new System.NotImplementedException(),
                CustomRoles.Shyboy => throw new System.NotImplementedException(),
                CustomRoles.Balancer => throw new System.NotImplementedException(),
                CustomRoles.ShrineMaiden => throw new System.NotImplementedException(),
                CustomRoles.Comebacker => throw new System.NotImplementedException(),
                CustomRoles.WhiteHacker => throw new System.NotImplementedException(),
                CustomRoles.WolfBoy => throw new System.NotImplementedException(),
                CustomRoles.NiceAddoer => throw new System.NotImplementedException(),
                CustomRoles.InSender => throw new System.NotImplementedException(),
                CustomRoles.Staff => throw new System.NotImplementedException(),
                CustomRoles.Efficient => throw new System.NotImplementedException(),
                CustomRoles.Psychic => throw new System.NotImplementedException(),
                CustomRoles.SwitchSheriff => throw new System.NotImplementedException(),
                CustomRoles.NiceLogger => throw new System.NotImplementedException(),
                CustomRoles.Android => throw new System.NotImplementedException(),
                CustomRoles.King => throw new System.NotImplementedException(),
                CustomRoles.AmateurTeller => throw new System.NotImplementedException(),
                CustomRoles.Cakeshop => throw new System.NotImplementedException(),
                CustomRoles.Snowman => throw new System.NotImplementedException(),
                CustomRoles.Stolener => throw new System.NotImplementedException(),
                CustomRoles.VentOpener => throw new System.NotImplementedException(),
                CustomRoles.VentHunter => throw new System.NotImplementedException(),
                CustomRoles.Walker => throw new System.NotImplementedException(),
                CustomRoles.CandleLighter => throw new System.NotImplementedException(),
                CustomRoles.Express => throw new System.NotImplementedException(),
                CustomRoles.Inspector => throw new System.NotImplementedException(),
                CustomRoles.Fortuner => throw new System.NotImplementedException(),
                CustomRoles.AllArounder => throw new System.NotImplementedException(),
                CustomRoles.Observer => throw new System.NotImplementedException(),
                CustomRoles.Satellite => throw new System.NotImplementedException(),
                CustomRoles.Merlin => throw new System.NotImplementedException(),
                CustomRoles.Analyzer => throw new System.NotImplementedException(),
                CustomRoles.Arsonist => throw new System.NotImplementedException(),
                CustomRoles.Egoist => throw new System.NotImplementedException(),
                CustomRoles.Jester => throw new System.NotImplementedException(),
                CustomRoles.Opportunist => throw new System.NotImplementedException(),
                CustomRoles.PlagueDoctor => throw new System.NotImplementedException(),
                CustomRoles.SchrodingerCat => throw new System.NotImplementedException(),
                CustomRoles.Terrorist => throw new System.NotImplementedException(),
                CustomRoles.Executioner => throw new System.NotImplementedException(),
                CustomRoles.Jackal => throw new System.NotImplementedException(),
                CustomRoles.Remotekiller => throw new System.NotImplementedException(),
                CustomRoles.Chef => throw new System.NotImplementedException(),
                CustomRoles.JackalMafia => throw new System.NotImplementedException(),
                CustomRoles.CountKiller => throw new System.NotImplementedException(),
                CustomRoles.GrimReaper => throw new System.NotImplementedException(),
                CustomRoles.Madonna => throw new System.NotImplementedException(),
                CustomRoles.Jackaldoll => throw new System.NotImplementedException(),
                CustomRoles.Workaholic => throw new System.NotImplementedException(),
                CustomRoles.Monochromer => throw new System.NotImplementedException(),
                CustomRoles.DoppelGanger => throw new System.NotImplementedException(),
                CustomRoles.MassMedia => throw new System.NotImplementedException(),
                CustomRoles.Chameleon => throw new System.NotImplementedException(),
                CustomRoles.Banker => throw new System.NotImplementedException(),
                CustomRoles.BakeCat => throw new System.NotImplementedException(),
                CustomRoles.Emptiness => throw new System.NotImplementedException(),
                CustomRoles.JackalAlien => throw new System.NotImplementedException(),
                CustomRoles.CurseMaker => throw new System.NotImplementedException(),
                CustomRoles.PhantomThief => throw new System.NotImplementedException(),
                CustomRoles.Fox => throw new System.NotImplementedException(),
                CustomRoles.Turncoat => throw new System.NotImplementedException(),
                CustomRoles.Vulture => throw new System.NotImplementedException(),
                CustomRoles.SantaClaus => throw new System.NotImplementedException(),
                CustomRoles.Missioneer => throw new System.NotImplementedException(),
                CustomRoles.Strawdoll => throw new System.NotImplementedException(),
                CustomRoles.Fool => throw new System.NotImplementedException(),
                CustomRoles.JackalWolf => throw new System.NotImplementedException(),
                CustomRoles.TaskPlayerB => throw new System.NotImplementedException(),
                CustomRoles.HASFox => throw new System.NotImplementedException(),
                CustomRoles.HASTroll => throw new System.NotImplementedException(),
                CustomRoles.MMArcher => throw new System.NotImplementedException(),
                CustomRoles.GM => throw new System.NotImplementedException(),
                CustomRoles.Driver => throw new System.NotImplementedException(),
                CustomRoles.Braid => throw new System.NotImplementedException(),
                CustomRoles.Vega => throw new System.NotImplementedException(),
                CustomRoles.Altair => throw new System.NotImplementedException(),
                CustomRoles.NotAssigned => throw new System.NotImplementedException(),
                CustomRoles.LastImpostor => throw new System.NotImplementedException(),
                CustomRoles.LastNeutral => throw new System.NotImplementedException(),
                CustomRoles.Workhorse => throw new System.NotImplementedException(),
                CustomRoles.Twins => throw new System.NotImplementedException(),
                CustomRoles.OneWolf => throw new System.NotImplementedException(),
                CustomRoles.Lovers => throw new System.NotImplementedException(),
                CustomRoles.RedLovers => throw new System.NotImplementedException(),
                CustomRoles.YellowLovers => throw new System.NotImplementedException(),
                CustomRoles.BlueLovers => throw new System.NotImplementedException(),
                CustomRoles.GreenLovers => throw new System.NotImplementedException(),
                CustomRoles.WhiteLovers => throw new System.NotImplementedException(),
                CustomRoles.PurpleLovers => throw new System.NotImplementedException(),
                CustomRoles.MadonnaLovers => throw new System.NotImplementedException(),
                CustomRoles.OneLove => throw new System.NotImplementedException(),
                CustomRoles.Amanojaku => throw new System.NotImplementedException(),
                CustomRoles.Faction => throw new System.NotImplementedException(),
                CustomRoles.Stack => throw new System.NotImplementedException(),
                CustomRoles.Amnesia => throw new System.NotImplementedException(),
                CustomRoles.DemonicCrusher => throw new System.NotImplementedException(),
                CustomRoles.DemonicTracker => throw new System.NotImplementedException(),
                CustomRoles.DemonicVenter => throw new System.NotImplementedException(),
                CustomRoles.DemonicSupporter => throw new System.NotImplementedException(),
                CustomRoles.Ghostbuttoner => throw new System.NotImplementedException(),
                CustomRoles.GhostNoiseSender => throw new System.NotImplementedException(),
                CustomRoles.GhostReseter => throw new System.NotImplementedException(),
                CustomRoles.GuardianAngel => throw new System.NotImplementedException(),
                CustomRoles.GhostRumour => throw new System.NotImplementedException(),
                CustomRoles.AsistingAngel => throw new System.NotImplementedException(),
                CustomRoles.Sunglasses => "Ｓ",
                _ => ""
            };
        }
        return "";
    }

    public static void SetRoleColor()
    {
        Main.roleColors = new Dictionary<CustomRoles, string>()
                {
                    // マッドメイト役職
                    {CustomRoles.SKMadmate, "#ff1919"},
                    //特殊クルー役職
                    //ニュートラル役職
                    {CustomRoles.Emptiness ,"#221d26"},
                    //HideAndSeek
                    {CustomRoles.HASFox, "#e478ff"},
                    {CustomRoles.HASTroll, "#00ff00"},
                    //TaskBattle
                    {CustomRoles.TaskPlayerB, "#9adfff"},
                    // GM
                    {CustomRoles.GM, "#ff5b70"},

                    //属性
                    {CustomRoles.LastImpostor, "#ff1919"},
                    {CustomRoles.LastNeutral,"#cccccc"},
                    {CustomRoles.Workhorse, "#00ffff"},
                    {CustomRoles.Twins, "#80cf48"},
                    {CustomRoles.OneWolf , "#ff1919"},

                    { CustomRoles.Watching, "#800080"},
                    {CustomRoles.Speeding, "#33ccff"},
                    {CustomRoles.Moon,"#ffff33"},
                    {CustomRoles.Guesser,"#999900"},
                    {CustomRoles.Lighting,"#ec6800"},
                    {CustomRoles.Management,"#cee4ae"},
                    {CustomRoles.Connecting,"#96514d"},
                    {CustomRoles.Serial,"#ff1919"},
                    {CustomRoles.PlusVote,"#93ca76"},
                    {CustomRoles.Opener,"#007bbb"},
                    {CustomRoles.Revenger,"#ffcc99"},
                    {CustomRoles.Seeing,"#61b26c"},
                    {CustomRoles.Autopsy,"#80ffdd"},
                    {CustomRoles.Tiebreaker,"#00552e"},
                    {CustomRoles.Guarding, "#7b68ee"},
                    {CustomRoles.MagicHand , "#dea785"},
                    {CustomRoles.Powerful , "#f08e39"},
                    {CustomRoles.Stack , "#b55f47"},
                    //{CustomRoles.AntiTeleporter,"#dea785"},
                    //デバフ
                    { CustomRoles.NonReport,"#006666"},
                    {CustomRoles.Notvoter,"#6c848d"},
                    {CustomRoles.Water,"#003f8e"},
                    {CustomRoles.Clumsy,"#942343"},
                    {CustomRoles.Slacker,"#980098"},
                    {CustomRoles.Elector,"#544a47"},
                    {CustomRoles.Transparent,"#7b7c7d"},
                    {CustomRoles.Amnesia,"#4682b4"},
                    {CustomRoles.SlowStarter,"#ff00ff"},
                    {CustomRoles.InfoPoor ,"#555647"},
                    {CustomRoles.News, "#828282"},
                    {CustomRoles.Sunglasses , "#2e103d"},

                    //第三属性
                    { CustomRoles.Amanojaku,"#005243"},
                    {CustomRoles.Faction,"#c6a768"},
                    {CustomRoles.Lovers, "#ff6be4"},
                    {CustomRoles.RedLovers, "#d70035"},
                    {CustomRoles.YellowLovers, "#fac559"},
                    {CustomRoles.BlueLovers, "#6c9bd2"},
                    {CustomRoles.GreenLovers, "#00885a"},
                    {CustomRoles.WhiteLovers, "#fdede4"},
                    {CustomRoles.PurpleLovers, "#af0082"},
                    {CustomRoles.MadonnaLovers, "#f09199"},
                    {CustomRoles.OneLove , "#ff7961"},

                    // 幽霊役職
                    {CustomRoles.Ghostbuttoner,"#d0af4c"},
                    {CustomRoles.GhostNoiseSender, "#5aa698"},
                    {CustomRoles.GhostReseter , "#a87a71"},
                    {CustomRoles.GhostRumour , "#707cab"},
                    {CustomRoles.GuardianAngel,"#7cc0fc"},
                    {CustomRoles.DemonicTracker,"#824880"},
                    {CustomRoles.DemonicCrusher,"#522886"},
                    {CustomRoles.DemonicSupporter , "#351f1f"},
                    { CustomRoles.DemonicVenter ,"#635963"},
                    {CustomRoles.AsistingAngel,"#8da0b6"},

                    {CustomRoles.NotAssigned, "#ffffff"}
                };
    }
}